version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: Dockerfile-centos
      args:
        TIMEZONE: ${TIMEZONE}
        GIT_USER: ${GIT_USER}
        GIT_PASS: ${GIT_PASS}
        NGINX_PORT: ${NGINX_PORT}
        SSL_NGINX_PORT: ${SSL_NGINX_PORT}
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
      - mariadb
    volumes:
      - ./docker/settings/nginx/hosts:/etc/nginx/conf.d
      - ./docker/settings/nginx/logs:/var/log/nginx
      - ./project:/var/www
    networks:
      presta_net:
        ipv4_address: 172.18.0.10
    privileged: true
    stdin_open: true
    tty: true

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker
      dockerfile: Dockerfile-php
      args:
        TIMEZONE: ${TIMEZONE}
        PHP_FPM_PORT: ${PHP_FPM_PORT}
#    command: bash -c "chown -R prestashop:prestashop /var/www"
    links:
      - mariadb
    volumes:
      - ./docker/settings/php/php.ini:/usr/local/etc/php/php.ini
      - ./project:/var/www
    ports:
      - "9000:9000"
#    environment:
#      DB_HOST: mariadb
#      DB_PORT: ${MARIADB_PORT}
#      DB_DATABASE: ${MYSQL_DATABASE}
#      DB_USERNAME: ${MYSQL_USER}
#      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      presta_net:
        ipv4_address: 172.18.0.15
    depends_on:
      - "mariadb"
      - "elasticsearch"
    privileged: true
    stdin_open: true
    tty: true

  mariadb:
#    image: mariadb:10.2.29
    container_name: mariadb
#    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile-mariadb
      args:
        MARIADB_VER: ${DB_VER}
        MYSQL_PORT: ${MYSQL_PORT}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
#      - ./docker/settings/mysql:/etc/mysql/conf.d:ro
      - ./docker/settings/mysql/db:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/mysql:rw
      - ./docker/settings/mysql/dump:/dump
      - ./docker/settings/mysql/logs:/var/log/mysql:rw
    ports:
      - "3306:3306"
    networks:
      presta_net:
        ipv4_address: 172.18.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    privileged: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
    volumes:
      - /sessions
    networks:
      presta_net:
        ipv4_address: 172.18.0.30

  elasticsearch:
    image: elasticsearch:7.5.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      presta_net:
        ipv4_address: 172.18.0.40

volumes:
  dbdata:
    driver: local

networks:
  presta_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1