FROM centos:7

MAINTAINER Dmitriy Kostrub <dmitriy.kostrub@forforce.com>

ARG username="prestaking"
ARG password="presta"
ARG TIMEZONE
ARG GIT_USER
ARG GIT_PASS
ARG NGINX_PORT
ARG SSL_NGINX_PORT

# system update
RUN yum -y install git apt && yum -y update && yum -y reinstall glibc-common && yum clean all
RUN yum -y install yum-utils wget epel-release unzip curl tar openssl mc bash-completion gnupg vim yum glibc-locale-source glibc-langpack-ru
RUN wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

# Locale
RUN localedef -v -c -i ru_RU -f utf8 ru_RU.UTF-8; echo "";
ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU:ru
ENV LC_ALL ru_RU.UTF-8
RUN rm -f /etc/localtime
RUN ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime

# kubernetes
# RUN yum -y install etcd kubernetes flannel

# php
RUN yum -y install --enablerepo=remi-php72 php php-devel php-pear php-mysqlnd php-mbstring php-fpm php-mcrypt php-xml php-pdo hp-opcache --nogpgcheck php-pecl-memcached php-pecl-mysql

# nginx
RUN rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
RUN yum -y install nginx
RUN nginx

# Install Node, NVM, NPM and Grunt
RUN yum install -y gcc-c++ make \
    && curl -sL https://rpm.nodesource.com/setup_12.x | bash - \
    && yum install -y nodejs \
    && npm install -y -g yarn

# Install Code
#RUN git clone https://${GIT_USER}:${GIT_PASS}@git.forforce.com/shops/goodwinehome.com.ua.git ./project
#RUN composer install

#RUN mkdir /home/${username}
RUN useradd -s /bin/bash -d /home/${username} ${username} && echo "${username}:${password}" | chpasswd
#RUN chown -R ${username}:${username} /home/${username}
#RUN groupadd -g 2000 ${username} \
#    && useradd -d /home/${username} -u 2000 -g 2000 ${username} \
#    && usermod -u 2000 ${username}

# Install xdebug
#RUN pecl install xdebug-2.7.2 && \
 #   docker-php-ext-enable xdebug \

# mysql use
RUN mkdir /var/lib/mysql

# PHP use
#RUN mkdir /usr/local/etc/php/
#ADD settings/php/php.ini /usr/local/etc/php/
#RUN chmod 755 /usr/local/etc/php/php.ini

# web use
#RUN mkdir /var/www && mkdir /var/www

# phpMyAdmin use
#RUN cd /tmp/
#RUN wget https://files.phpmyadmin.net/phpMyAdmin/4.6.6/phpMyAdmin-4.6.6-all-languages.zip
#RUN mv phpMyAdmin-4.6.6-all-languages/* /var/www/phpmyadmin

# nginx use
ADD settings/nginx/hosts /etc/nginx/conf.d/
RUN chmod 755 -R /etc/nginx/conf.d
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf_bk
CMD ["nginx", "-g", "daemon off;"]
RUN chmod 755 /var/log/nginx/

ADD settings/nginx/ssl/mysite_com.crt /etc/nginx/ssl/
ADD settings/nginx/ssl/mysite_com.key /etc/nginx/ssl/
RUN chmod 755 /etc/nginx/ssl/mysite_com.crt
RUN chmod 755 /etc/nginx/ssl/mysite_com.key

# port
EXPOSE 80
EXPOSE 443